# Generated by Django 3.0.4 on 2020-03-10 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('total_rating', models.IntegerField(default=0)),
                ('totalnum_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorModuleRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rating', models.IntegerField(default=0)),
                ('totalnum_rating', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwk1.Module')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwk1.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], default='Please Select One', max_length=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwk1.Module')),
                ('professor', models.ManyToManyField(to='cwk1.Professor')),
            ],
        ),
    ]
